top_characters = [
    'Spider-Man',
    'X-Men',
    'Iron Man',
    'Wolverine',
    'Captain America',
    'Hulk',
    'Thor',
    'Fantastic Four',
    'Avengers',
    'Daredevil',
    'Human Torch',
    'Cyclops',
    'Storm',
    'Beast',
    'Colossus',
    'Sub-Mariner',
    'Archangel',
    'Nightcrawler',
    'Mr. Fantastic',
    'Thing',
    'Rogue',
    'Doctor Strange',
    'Iceman',
    'Invisible Woman',
    'Punisher',
    'Deadpool',
    'Silver Surfer',
    'Black Panther',
    'Captain Marvel (Carol Danvers)',
    'Professor X',
    'She-Hulk (Jennifer Walters)',
    'Gambit',
    'Black Widow',
    'Cable',
    'Nick Fury',
    'Vision',
    'Scarlet Witch',
    'Psylocke',
    'Magneto',
    'Bishop',
    'Cannonball',
    'Havok',
    'Wasp',
    'Spider-Man (Ultimate)',
    'X-Force',
    'Emma Frost',
    'Ghost Rider (Johnny Blaze)',
    'Quicksilver',
    'Hawkeye',
    'New Mutants',
    'Polaris',
    'Hank Pym',
    'Loki',
    'Doctor Doom',
    'Wonder Man',
    'Defenders',
    'Alpha Flight',
    'Jubilee',
    'Excalibur',
    'Banshee',
    'Sabretooth',
    'Spider-Girl (May Parker)',
    'Dazzler',
    'Warpath',
    'X-Men (Ultimate)',
    'Sunspot',
    'The Winter Soldier',
    'Captain Marvel (Mar-Vell)',
    'Juggernaut',
    'Kitty Pryde',
    'Thunderbolts',
    'Odin',
    'Banshee (Theresa Rourke)',
    'Hercules',
    'Two-Gun Kid',
    'Sif',
    'Nova',
    'Norman Osborn',
    'Iron Fist (Danny Rand)',
    'Domino',
    'Forge',
    'Rawhide Kid',
    'Mystique',
    'Falcon',
    'Red Skull',
    'Moon Knight',
    'Elektra',
    'Exiles',
    'Galactus',
    'Adam Warlock',
    'Luke Cage',
    'X-Factor',
    'J. Jonah Jameson',
    'Kingpin',
    'Quasar (Phyla-Vell)',
    'Black Knight',
    'Shatterstar',
    'Spider-Woman (Jessica Drew)',
    'X-Man',
    'Lilandra',
    'Captain Britain',
    'Mary Jane Watson',
]